name: Tabak Monitor

on:
  schedule:
    - cron: "0 5 * * *"   # runs daily ~07:00 Zurich time
  workflow_dispatch:       # allows manual runs

permissions:
  contents: write          # needed to commit state.json back

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml pillow

      - name: Run scraper
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python scraper.py

      - name: Commit state if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "tabak-bot"
            git config user.email "bot@users.noreply.github.com"
            git add state.json
            git commit -m "Update state [skip ci]"
            git push
          fi
